export { default as PageBorders } from "./PageBorders.vue"
export { default as Preloader } from "./PreloaderComponent.vue"
export { default as MobileMenu } from "./MobileMenu.vue"
export { default as SvgIcon } from "./SvgIcon.vue"
export { default as PageHeader } from "./PageHeader.vue"
export { default as PageContent } from "./PageContent.vue"
