export { default as WorksList } from "./WorksList.vue"
export { default as WorkItem } from "./WorkItem.vue"
export { default as WorkImages } from "./WorkImages.vue"
export { default as WorkDetails } from "./WorkDetails.vue"
export { default as ModalBox } from "./ModalBox.vue"
