name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Git commands
        run: |
          git config --global user.email "mail@evren.dev"
          git config --global user.name "evrendev"

          # Change Directory
          cd ./src/frontend

          # Install depedencies
          npm i

          # build
          npm run build

          # Change Directory
          cd ../../

          echo 'Deploying to gh-pages...'

          git add dist -f
          git commit -m 'Deploy' 
          git subtree push --prefix ./dist origin gh-pages   --force

          echo 'Done'
        env:
          github-token: ${{ secrets.GH_TOKEN }}
